global using Microsoft.Playwright;
global using QATools.Actions;
global using QATools.Constants;
global using QATools.Pages;
global using QATools.Pattern;
global using TechTalk.SpecFlow;
global using BoDi;
global using NUnit.Framework;
global using Microsoft.Extensions.Configuration;
global using System.Reflection;
global using NUnit.Framework.Interfaces;
global using QATools.Config;
global using QATools.Exceptions;
global using QATools.Extensions;
global using static Microsoft.Playwright.Assertions;